#!/usr/bin/env python

from os import path
import sys
import zipfile
import gzip

SHELL_FILES = [
    "emscripten/logo.svg",
    "emscripten/shell.js",
    "emscripten/shell.css",
]

def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(f"Usage: {argv[0]} <file.html> <ouptut.zip>")
        return 1

    input = argv[1]
    output = argv[2]

    basename = path.splitext(input)[0]
    project_name = path.basename(basename)

    with zipfile.ZipFile(
        file=output,
        mode='w',
        compression=zipfile.ZIP_DEFLATED,
    ) as archive:
        print(f"Packing {basename}.html")
        archive.write(basename + ".html", "index.html")

        print(f"Packing {basename}.js")
        archive.write(basename + ".js", project_name + ".js")

        print(f"Packing {basename}.wasm")
        pack_gzip(archive, basename + ".wasm", project_name + ".wasmz")

        print(f"Packing {basename}.data")
        if path.exists(basename + ".data"):
            archive.write(basename + ".data", project_name + ".data.pck")

        print(f"Packing {basename}.wasm.debug.wasm")
        if path.exists(basename + ".wasm.debug.wasm"):
            archive.write(basename + ".wasm.debug.wasm", project_name + ".wasm.debug.wasm")

        archive.mkdir("emscripten")
        script_dir = path.dirname(__file__)
        for file in SHELL_FILES:
            file_path = path.join(script_dir, file)
            print(f"Packing {file_path}")
            archive.write(file_path, file)

def pack_gzip(archive: zipfile.ZipFile, path: str, arc_name: str) -> None:
    with open(path, "rb") as file:
        data = file.read()

    archive.writestr(arc_name, gzip.compress(data), compress_type=zipfile.ZIP_STORED)

if __name__ == "__main__":
    sys.exit(main(sys.argv))
